// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/indexPage/Banner.vue')['default']
    BreadCrumb: typeof import('./src/components/global/BreadCrumb.vue')['default']
    Cards: typeof import('./src/components/products/Cards.vue')['default']
    Cart01: typeof import('./src/components/carts/Cart01.vue')['default']
    Cart02: typeof import('./src/components/carts/Cart02.vue')['default']
    Cart03: typeof import('./src/components/carts/Cart03.vue')['default']
    CartInfo: typeof import('./src/components/carts/CartInfo.vue')['default']
    CartLogin: typeof import('./src/components/carts/CartLogin.vue')['default']
    CartProducts: typeof import('./src/components/carts/CartProducts.vue')['default']
    CartProgress: typeof import('./src/components/carts/CartProgress.vue')['default']
    Categories: typeof import('./src/components/admin/Categories.vue')['default']
    Categroy: typeof import('./src/components/products/Categroy.vue')['default']
    Comment: typeof import('./src/components/product/Comment.vue')['default']
    Description: typeof import('./src/components/product/Description.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FacebookSignIn: typeof import('./src/components/signIn/FacebookSignIn.vue')['default']
    Footer: typeof import('./src/components/global/Footer.vue')['default']
    GithubSignIn: typeof import('./src/components/signIn/GithubSignIn.vue')['default']
    GoogleSignIn: typeof import('./src/components/signIn/GoogleSignIn.vue')['default']
    GoTop: typeof import('./src/components/global/GoTop.vue')['default']
    Header: typeof import('./src/components/product/Header.vue')['default']
    Info: typeof import('./src/components/member/Info.vue')['default']
    Loading: typeof import('./src/components/global/Loading.vue')['default']
    Menu: typeof import('./src/components/indexPage/Menu.vue')['default']
    More: typeof import('./src/components/product/More.vue')['default']
    Navbar: typeof import('./src/components/admin/Navbar.vue')['default']
    Order: typeof import('./src/components/member/Order.vue')['default']
    Pagination: typeof import('./src/components/products/Pagination.vue')['default']
    Payment: typeof import('./src/components/product/Payment.vue')['default']
    Products: typeof import('./src/components/admin/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopNow: typeof import('./src/components/indexPage/ShopNow.vue')['default']
    Sidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
    Sort: typeof import('./src/components/products/Sort.vue')['default']
    Subscribe: typeof import('./src/components/indexPage/Subscribe.vue')['default']
  }
}
