// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminCategories: typeof import('./src/components/admin/Categories.vue')['default']
    AdminNavbar: typeof import('./src/components/admin/Navbar.vue')['default']
    AdminOrders: typeof import('./src/components/admin/Orders.vue')['default']
    AdminProducts: typeof import('./src/components/admin/Products.vue')['default']
    AdminSidebar: typeof import('./src/components/admin/Sidebar.vue')['default']
    CartsCart01: typeof import('./src/components/carts/Cart01.vue')['default']
    CartsCart02: typeof import('./src/components/carts/Cart02.vue')['default']
    CartsCart03: typeof import('./src/components/carts/Cart03.vue')['default']
    CartsCartInfo: typeof import('./src/components/carts/CartInfo.vue')['default']
    CartsCartLogin: typeof import('./src/components/carts/CartLogin.vue')['default']
    CartsCartProducts: typeof import('./src/components/carts/CartProducts.vue')['default']
    CartsCartProgress: typeof import('./src/components/carts/CartProgress.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GlobalBreadCrumb: typeof import('./src/components/global/BreadCrumb.vue')['default']
    GlobalFooter: typeof import('./src/components/global/Footer.vue')['default']
    GlobalGoTop: typeof import('./src/components/global/GoTop.vue')['default']
    GlobalLoading: typeof import('./src/components/global/Loading.vue')['default']
    GlobalNavbar: typeof import('./src/components/global/Navbar.vue')['default']
    IndexPageBanner: typeof import('./src/components/indexPage/Banner.vue')['default']
    IndexPageMenu: typeof import('./src/components/indexPage/Menu.vue')['default']
    IndexPageShopNow: typeof import('./src/components/indexPage/ShopNow.vue')['default']
    IndexPageSubscribe: typeof import('./src/components/indexPage/Subscribe.vue')['default']
    MemberInfo: typeof import('./src/components/member/Info.vue')['default']
    MemberNavbar: typeof import('./src/components/member/Navbar.vue')['default']
    MemberOrder: typeof import('./src/components/member/Order.vue')['default']
    ProductComment: typeof import('./src/components/product/Comment.vue')['default']
    ProductDescription: typeof import('./src/components/product/Description.vue')['default']
    ProductHeader: typeof import('./src/components/product/Header.vue')['default']
    ProductMore: typeof import('./src/components/product/More.vue')['default']
    ProductPayment: typeof import('./src/components/product/Payment.vue')['default']
    ProductsCards: typeof import('./src/components/products/Cards.vue')['default']
    ProductsCategroy: typeof import('./src/components/products/Categroy.vue')['default']
    ProductsPagination: typeof import('./src/components/products/Pagination.vue')['default']
    ProductsSort: typeof import('./src/components/products/Sort.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInFacebookSignIn: typeof import('./src/components/signIn/FacebookSignIn.vue')['default']
    SignInGithubSignIn: typeof import('./src/components/signIn/GithubSignIn.vue')['default']
    SignInGoogleSignIn: typeof import('./src/components/signIn/GoogleSignIn.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
